--- #YAML:1.0
name:                     Labyrinth::Plugin::Wiki
version:                  1.03
abstract:                 Wiki plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                     5.006
  Labyrinth:                5.03
  Algorithm::Diff:          0
  VCS::Lite:                0
recommends:
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  Labyrinth::Plugin::Wiki:
    file:     lib/Labyrinth/Plugin/Wiki.pm
    version:  1.03
  Labyrinth::Plugin::Wiki::Text:
    file:     lib/Labyrinth/Plugin/Wiki/Text.pm
    version:  1.03

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Wiki

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
